name: learn-git

on:
  - push

jobs:
  job1:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python
      - run: print("hello")
  job2:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello
        run: echo "Hello every one"
