name: main

on:
  push:
    branches: [main, test-me-*]
  workflow_dispatch:
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py37"]'
      os: windows-latest
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py37", "py38", "py39"]'
      os: ubuntu-latest
